### ISSUE TITLE
Installing from REDCap Repo disabled due to "PHP version compatibility"

### ISSUE THREAD

**Issue by ChemiKyle** [lsgs/redcap-report-scheduler#5]
Hey Luke, just wanted to give you a heads up that the REDCap Repo page disables installation due to a "PHP incompatibility"

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/20332546/137149680-6980b2de-3b81-48e9-9f51-5d2222bb8be8.png">

This is affecting [one of our modules too](https://github.com/ctsit/qr_code_shortcut/issues/15), but none of the others available in the repo! Clearly targeted harassment; perhaps Vanderbilt is frightened of us since UF and MCRI contributed to the most downloaded modules this year.

I'm not sure what's causing this, I'm pretty confident it's a REDCap Repo issue; I'll update here if I find anything out.

**Comment by lsgs** [comment]
Hello Kyle,
Thanks for the info. Yeah that is weird, isn't it. It's running fine on our PHP 7.2.24, fwiw! Interested in what you hear about it...
Cheers,
Luke

.
________________________________
From: Kyle Chesney ***@***.***>
Sent: Thursday, 14 October 2021 01:14
To: lsgs/redcap-report-scheduler ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lsgs/redcap-report-scheduler] Installing from REDCap Repo disabled due to "PHP version compatibility" (#5)


Hey Luke, just wanted to give you a heads up that the REDCap Repo page disables installation due to a "PHP incompatibility"

[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F20332546%2F137149680-6980b2de-3b81-48e9-9f51-5d2222bb8be8.png&data=04%7C01%7C%7C1325a2da004840757a6e08d98e53b8d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697312492709698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BNLq1952VMXABGP%2B5iq5RXHxALhgt9pcdFf%2F4dp4%2B5w%3D&reserved=0>

This is affecting one of our modules too<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fctsit%2Fqr_code_shortcut%2Fissues%2F15&data=04%7C01%7C%7C1325a2da004840757a6e08d98e53b8d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697312492709698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=d0XBEE1IwM8wUdfl2Pi1QX1F0J1OG4t9Kc2ja6hL6r4%3D&reserved=0>, but none of the others available in the repo! Clearly targeted harassment; perhaps Vanderbilt is frightened of us since UF and MCRI contributed to the most downloaded modules this year.

I'm not sure what's causing this, I'm pretty confident it's a REDCap Repo issue; I'll update here if I find anything out.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flsgs%2Fredcap-report-scheduler%2Fissues%2F5&data=04%7C01%7C%7C1325a2da004840757a6e08d98e53b8d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697312492719656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gLAI7Ec%2FCPe3I02RvBeZgHs5a65lr5uvUD9oliHOZQ0%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABYZPSQ5GBZ3BNH7JYT7LNTUGWH27ANCNFSM5F5J6DAQ&data=04%7C01%7C%7C1325a2da004840757a6e08d98e53b8d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697312492729613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HrAb1nSllQLIMpZd5MZu2ocha4uj2QO0LyXqvLM%2FFPg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C1325a2da004840757a6e08d98e53b8d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697312492729613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5Jy56U7cP0a4UZiA80bCw8Z%2BWzvLP1V35wWt0aLzEYE%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C1325a2da004840757a6e08d98e53b8d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697312492739567%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=B%2FpH3Dx0XmOrPQAZkVkA%2FS9y8E6FgpOvRzYGhPb00cM%3D&reserved=0>.

**Comment by ChemiKyle** [comment]
Hi Luke,

I heard back from Mark McEver:

> It looks like the Report Scheduler module was accidentally submitted twice under slightly different names. One of the submissions was obviously invalid, so I disabled it. You should now see only a single version of the Report Scheduler in the repo, which you should be able to download. We’ve since improved automation around submissions which should prevent this type of invalid submission going forward. Thanks for reporting this!
